name: Socat Standalone on Bullseye

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build socat
      run: docker build -t socat_standalone_bullseye:$(date +%s) -f socat_standalone/containers/debian/bullseye/Dockerfile .
